apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-wcoj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-wcoj
    app.kubernetes.io/part-of: e2e-springboot
  name: devfile-sample-java-springboot-basic-wcoj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: devfile-sample-java-springboot-basic-wcoj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: devfile-sample-java-springboot-basic-wcoj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-unio-tenant/e2e-springboot/devfile-sample-java-springboot-basic-wcoj@sha256:e31ca80482fddb3ba1702918a73337512267d6875a5226a8cd4160c5fd8bcf46
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
